spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to bmwas-consulting accounts related prod APIs "
  contactDetails:
    name: "Mamadou BAH - Product Owner"
    email: "mamadou.bah@bmwas-consulting.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384