  spring:
    application:
      name: "gatewayserver"
    config:
      import: "optional:configserver:http://localhost:8071/"
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false
            lowerCaseServiceId: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoint:
      gateway:
        enabled: true
      health:
        probes:
          enabled: true
    info:
      env:
        enabled: true

  info:
    app:
      name: "gatewayserver"
      description: "bmwas consulting Gateway Server Application"
      version: "1.0.0"

  logging:
    level:
      com:
        mamadou4bah:
          gatewayserver: DEBUG

