spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to bmwas-consulting cards related QA APIs "
  contactDetails:
    name: "Mamadou BAH - QA Lead"
    email: "mamadou.bah@bmwas-consulting.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267